config/routes.rb
Rails.application.routes.draw do

  resources :games
  root 'sessions#welcome'
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'

  get 'sessions', to: 'sessions#show'
  post 'sessions', to: 'sessions#show', as: :sessions_show
  get 'authorized', to: 'sessions#page_requires_login'

  get 'avalons', to: 'avalons#show', as: :avalon

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boards/base.rb
module Boards
  class Base < ApplicationRecord
    self.abstract_class = true
    belongs_to :game
    has_many :quests
  end
end

app/models/characters/base.rb
module Characters
  class Base < ApplicationRecord
    self.abstract_class = true
    belongs_to :player

    def can_see
      Set[]
    end
  end
end

app/models/characters/merlin.rb
module Characters
  class Merlin < Base
    def initialize
      @goodness = :good
    end

    def can_see
      Set[Morgana, Assassin, Minion]
    end
  end
end

app/models/characters/minion.rb
module Characters
  class Servant < Base
    def initialize
      @goodness :bad
    end

    def can_see
      Set[Mordred, Morgana, Assassin, Minion]
    end
    
  end
end

app/models/game.rb
class Game < ApplicationRecord
  # Contains many players
  # 5 >= people <= 10 players in a game
  has_many :players
  has_one :board

end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  has_one :character
  has_many :questinfo


end

app/models/quest.rb
class Quest < ApplicationRecord
  has_many :turns
  has_many :questinfo
end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :quest
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?
  helper_method :admin?
  helper_method :list_online_users
  helper_method :list_online_users_array

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def admin?
    user_id = User.find_by(id: session[:user_id])
    user_id.username == "gubaee"
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end

  def list_online_users
    @users ||= User.where(online: true)
  end

  def list_online_users_array
    @users ||= User.where(online: true)
    @array = []
    @users.each do |user|
      @array.append(user.username)
    end
    return @array
  end
end

app/controllers/avalons_controller.rb
class AvalonsController < ApplicationController
  def show

  end

  def show
    # def run(players_username:)
    input_from_web = 7
    role = Avalon::Role.new(7)
    @shuffled_list_of_roles = role.shuffled_list_of_roles

    # hard coded value of list of players
    @players_username = ["apple", "blueberry", "strawberry", "mango", "banana", "peach", "lemon"]
    # initialize empty hashmap
    @players_map = {}
    # give a role to each players
    for i in 0..players_username.length()
      players_map[players_username[i]] = shuffled_list_of_roles[i]
    end
  end

  def setup_game
    # ::Avalon::Avalonboard.run(list_online_users_array)
    # ::Avalon::Avalonboard.run
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new

  end

  def show
    @games = Game.all
    # byebug
    @clicked = params[:game]
  end

  def create
    @user = User.find_by(username: params[:username])

    # set user status to online
    
    # byebug
    @user.update_attribute(:online, true)

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      redirect_to '/login'
    end

  end

  def destroy
    # byebug

    # set user status to offline
    # byebug
    @user = User.find_by_id(session[:user_id])
    @user.update_attribute(:online, false)
    session.destroy
    redirect_to '/welcome'
  end

  def login
  end

  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # this method allows new, and create to skip the authorized method requirement
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def show

  end

  def create

    begin
      @user = User.create(params.require(:user).permit(:username, :password))
      @user.save
      flash[:notice] = "Sucessfully created an account!"
      session[:user_id] = @user.id

      redirect_to '/welcome'
    rescue
      flash[:notice] = "Username already exist!"
      redirect_to '/welcome'
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avalons_helper.rb
module AvalonsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardgameApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>

  <body>

    <%= render "shared/nav" %>
    <%= render "shared/nav2" %>
    <%#= render "shared/flash" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice"><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="flash alert"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home", '/welcome', class: "nav-link" %>
  <% if logged_in? %>
    <% if admin? %>
      <%= link_to "Make", '/games', class: "nav-link" %>
    <% end %>
    <%= link_to "Games", '/sessions', class: "nav-link" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Create User", new_user_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link"%>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/shared/_nav2.html.erb
<!-- List of online users -->
<div class="sidenav">
  <% @users = list_online_users %>
  <h5>Online</h5>
  <% @users.each do |user| %>
    <p><%=user.username%></p>
  <% end%>
</div>

app/views/shared/flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice"><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="flash alert"><%= flash[:alert] %></div>
<% end %>