config/routes.rb
Rails.application.routes.draw do

  resources :games
  root 'sessions#welcome'
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'

  get 'sessions', to: 'sessions#show'
  post 'sessions', to: 'sessions#show', as: :sessions_show
  get 'authorized', to: 'sessions#page_requires_login'

  get 'avalons', to: 'avalons#show', as: :avalon

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boards/base.rb
module Boards
  class Base < ApplicationRecord
    self.abstract_class = true
    belongs_to :game
    has_many :quests
  end
end

app/models/characters/base.rb
module Characters
  class Base < ApplicationRecord
    self.abstract_class = true
    belongs_to :player

    def can_see
      Set[]
    end
  end
end

app/models/characters/merlin.rb
module Characters
  class Merlin < Base
    def initialize
      @goodness = :good
    end

    def can_see
      Set[Morgana, Assassin, Minion]
    end
  end
end

app/models/characters/minion.rb
module Characters
  class Servant < Base
    def initialize
      @goodness :bad
    end

    def can_see
      Set[Mordred, Morgana, Assassin, Minion]
    end
    
  end
end

app/models/characters/mordred.rb
module Characters
  class Mordred < Base
    def initialize
      @goodness :bad
    end

    def can_see
      Set[Mordred, Morgana, Assassin, Minion]
    end

  end
end

app/models/characters/morgana.rb
module Characters
  class Morgana < Base
    def initialize
      @goodness :bad
    end

    def can_see
      Set[Mordred, Morgana, Assassin, Minion]
    end

  end
end

app/models/characters/servant.rb
module Characters
  class Servant < Base
    def initialize
      @goodness :good
    end
    
  end
end

app/models/game.rb
class Game < ApplicationRecord
  # Contains many players
  # 5 >= people <= 10 players in a game
  has_many :players
  has_one :board

end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  has_one :character
  has_many :questinfo


end

app/models/quest.rb
class Quest < ApplicationRecord
  has_many :turns
  has_many :questinfo
end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :quest
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?
  helper_method :admin?
  helper_method :list_online_users
  helper_method :list_online_users_array

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def admin?
    user_id = User.find_by(id: session[:user_id])
    user_id.username == "gubaee"
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end

  def list_online_users
    @users ||= User.where(online: true)
  end

  def list_online_users_array
    @users ||= User.where(online: true)
    @array = []
    @users.each do |user|
      @array.append(user.username)
    end
    return @array
  end
end

app/controllers/avalons_controller.rb
class AvalonsController < ApplicationController
  def show

  end

  def show
    # def run(players_username:)
    input_from_web = 7
    role = Avalon::Role.new(7)
    @shuffled_list_of_roles = role.shuffled_list_of_roles

    # hard coded value of list of players
    @players_username = ["apple", "blueberry", "strawberry", "mango", "banana", "peach", "lemon"]
    # initialize empty hashmap
    @players_map = {}
    # give a role to each players
    for i in 0..players_username.length()
      players_map[players_username[i]] = shuffled_list_of_roles[i]
    end
  end

  def setup_game
    # ::Avalon::Avalonboard.run(list_online_users_array)
    # ::Avalon::Avalonboard.run
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new

  end

  def show
    @games = Game.all
    # byebug
    @clicked = params[:game]
  end

  def create
    @user = User.find_by(username: params[:username])

    # set user status to online
    
    # byebug
    @user.update_attribute(:online, true)

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      redirect_to '/login'
    end

  end

  def destroy
    # byebug

    # set user status to offline
    # byebug
    @user = User.find_by_id(session[:user_id])
    @user.update_attribute(:online, false)
    session.destroy
    redirect_to '/welcome'
  end

  def login
  end

  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # this method allows new, and create to skip the authorized method requirement
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def show

  end

  def create

    begin
      @user = User.create(params.require(:user).permit(:username, :password))
      @user.save
      flash[:notice] = "Sucessfully created an account!"
      session[:user_id] = @user.id

      redirect_to '/welcome'
    rescue
      flash[:notice] = "Username already exist!"
      redirect_to '/welcome'
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avalons_helper.rb
module AvalonsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class="form-group">
  <%= form_for @user do |f|%>
    <%= f.label :username%><br>
    <%= f.text_field :username, class: "form-control"%><br>
    <%= f.label :password%><br>
    <%= f.password_field :password, class: "form-control"%><br>
    <%= f.submit "Create", class: "btn btn-primary" %>
    <%#= button_to "Login", '/login', class:"btn btn-primary", method: :get%>
  <%end%>
</div>